import { Task, CalendarEvent, MeetingType, Booking, Achievement, ReflectionLog, FocusRecord, UserStats, UserProfile } from './types';

export const INITIAL_PROFILE: UserProfile = {
  id: 'user_1',
  firstName: 'Alex',
  lastName: 'Morgan',
  email: 'alex.morgan@operating.system',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  isGoogleConnected: false,
  joinedAt: '2026-05-01T00:00:00Z',
};

export const INITIAL_STATS: UserStats = {
  xp: 1420,
  level: 3,
  focusStreak: 6,
  taskStreak: 9,
  lastFocusDate: '2026-06-14',
  lastTaskDate: '2026-06-14',
};

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'deep_work_1',
    title: 'First Deep Work',
    description: 'Complete your first focused deep work session.',
    xpReward: 100,
    iconName: 'Zap',
    thresholdValue: 1,
    metric: 'focusSessionCount',
  },
  {
    id: 'deep_work_10',
    title: 'Focus Specialist',
    description: 'Complete 10 deep work sessions.',
    xpReward: 300,
    iconName: 'Flame',
    thresholdValue: 10,
    metric: 'focusSessionCount',
  },
  {
    id: 'focus_50_hours',
    title: 'Momentum Master',
    description: 'Accumulate 50 total focused hours.',
    xpReward: 500,
    iconName: 'Trophy',
    thresholdValue: 50,
    metric: 'focusHours',
  },
  {
    id: 'tasks_10',
    title: 'Task Conqueror',
    description: 'Mark 10 supporting or priority tasks as complete.',
    xpReward: 150,
    iconName: 'CheckCircle2',
    thresholdValue: 10,
    metric: 'tasks',
  },
  {
    id: 'streak_7',
    title: 'Unstoppable Momentum',
    description: 'Maintain a 7-day focus streak.',
    xpReward: 250,
    iconName: 'Activity',
    thresholdValue: 7,
    metric: 'daysStreak',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Deep work: Momenzi architecture & database roadmap',
    description: 'Establish state sync layout, configure tables schema outline, and integrate local persistence.',
    dueDate: '2026-06-15',
    duration: 90,
    priority: 'high',
    status: 'In Progress',
    category: 'Work',
    isTopThree: true,
    isTopFive: false,
    tags: ['Architecture', 'Milestone'],
    recurrence: 'none',
    createdAt: '2026-06-14T10:00:00Z',
  },
  {
    id: 'task_2',
    title: 'Review design feedback and brand identity asset',
    description: 'Go through the review comments regarding the soft shadows, rounding guidelines and navy gradient.',
    dueDate: '2026-06-15',
    duration: 30,
    priority: 'medium',
    status: 'Complete',
    category: 'Work',
    isTopThree: true,
    isTopFive: false,
    tags: ['Design', 'UX'],
    recurrence: 'none',
    createdAt: '2026-06-14T11:00:00Z',
  },
  {
    id: 'task_3',
    title: 'Write high-converting landing page tagline copy',
    description: 'Draft the main header and supporting copies utilizing emotional hooks & premium tone.',
    dueDate: '2026-06-15',
    duration: 60,
    priority: 'high',
    status: 'Not Started',
    category: 'Work',
    isTopThree: true,
    isTopFive: false,
    tags: ['Copywriting'],
    recurrence: 'none',
    createdAt: '2026-06-15T08:00:00Z',
  },
  {
    id: 'task_4',
    title: 'Sunsama-style core scheduler alignment',
    description: 'Align meeting types buffer times and check conflicts with vacation blocks.',
    dueDate: '2026-06-15',
    duration: 45,
    priority: 'medium',
    status: 'Not Started',
    category: 'Personal',
    isTopThree: false,
    isTopFive: true,
    tags: ['Planning'],
    recurrence: 'daily',
    createdAt: '2026-06-15T08:30:00Z',
  },
  {
    id: 'task_5',
    title: 'Gym workout: Lower body mobility & hamstring stretch',
    description: 'Focus on full lunges, dumbbell squats, deep stretches to reset lower spine.',
    dueDate: '2026-06-15',
    duration: 60,
    priority: 'medium',
    status: 'Complete',
    category: 'Health',
    isTopThree: false,
    isTopFive: true,
    tags: ['Fitness'],
    recurrence: 'weekly',
    createdAt: '2026-06-15T07:00:00Z',
  },
  {
    id: 'task_6',
    title: 'Read 15 pages of "Atomic Habits" by James Clear',
    description: 'Reflect on environment structure design chapter for cue adjustments.',
    dueDate: '2026-06-15',
    duration: 20,
    priority: 'low',
    status: 'Complete',
    category: 'Learning',
    isTopThree: false,
    isTopFive: true,
    tags: ['Reading'],
    recurrence: 'daily',
    createdAt: '2026-06-15T07:15:00Z',
  },
  {
    id: 'task_7',
    title: 'Configure booking availability buffer limits',
    description: 'Set custom breaks of 15 mins between bookings so strategy sessions have sufficient buffer.',
    dueDate: '2026-06-16',
    duration: 15,
    priority: 'low',
    status: 'Not Started',
    category: 'Work',
    isTopThree: false,
    isTopFive: true,
    tags: ['Bookings'],
    recurrence: 'none',
    createdAt: '2026-06-15T12:00:00Z',
  },
  {
    id: 'task_8',
    title: 'Weekly financial overview & expense report',
    description: 'Categorize receipts, enter spreadsheet summaries & update business metrics.',
    dueDate: '2026-06-17',
    duration: 40,
    priority: 'low',
    status: 'Not Started',
    category: 'Personal',
    isTopThree: false,
    isTopFive: false,
    tags: ['Finance'],
    recurrence: 'none',
    createdAt: '2026-06-15T10:00:00Z',
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'event_1',
    title: 'Roadmap Planning & Architecture Review',
    description: 'Interactive session to lay down components structure',
    startTime: '2026-06-15T09:00:00Z',
    endTime: '2026-06-15T10:30:00Z',
    space: 'Work',
  },
  {
    id: 'event_2',
    title: 'Design Team Sync & Feedback Round',
    description: 'Collaborative feedback round with designers',
    startTime: '2026-06-15T11:00:00Z',
    endTime: '2026-06-15T11:30:00Z',
    space: 'Work',
  },
  {
    id: 'event_3',
    title: 'Marketing Review Session',
    description: 'Identify conversion targets',
    startTime: '2026-06-15T15:00:00Z',
    endTime: '2026-06-15T16:00:00Z',
    space: 'Work',
  },
  {
    id: 'event_4',
    title: 'Gym Workout Routine',
    description: 'Legs, core and hamstrings mobility restretch',
    startTime: '2026-06-15T18:00:00Z',
    endTime: '2026-06-15T19:00:00Z',
    space: 'Health',
  },
  {
    id: 'event_5',
    title: 'Strategy Discussion with Client',
    description: 'Consultation about project deadlines & deliverables',
    startTime: '2026-06-16T14:00:00Z',
    endTime: '2026-06-16T15:00:00Z',
    space: 'Work',
  }
];

export const INITIAL_MEETING_TYPES: MeetingType[] = [
  {
    id: 'meet_15',
    title: 'Intro Call',
    duration: 15,
    description: 'A quick introductory conversation to align on objectives, fit, and basic project scopes.',
    slug: 'intro-15m',
    isActive: true,
  },
  {
    id: 'meet_30',
    title: 'Consultation Session',
    duration: 30,
    description: 'Medium scale deep-dive regarding operational blockages and direct solution alignment.',
    slug: 'consult-30m',
    isActive: true,
  },
  {
    id: 'meet_60',
    title: 'Strategy Session',
    duration: 60,
    description: 'In-depth workflow planning, milestones layout, and calendar blockages review.',
    slug: 'strategy-60m',
    isActive: true,
  },
  {
    id: 'meet_90',
    title: 'Deep Dive Session',
    duration: 90,
    description: 'Intense collaborative execution, pair architecture building, and system integration.',
    slug: 'deepdive-90m',
    isActive: true,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book_1',
    meetingTypeId: 'meet_30',
    guestName: 'Sarah Jenkins',
    guestEmail: 'sarah@stripe-infra.com',
    guestNotes: 'Keen to explore custom scheduling setup and API structures.',
    startTime: '2026-06-16T10:00:00Z',
    endTime: '2026-06-16T10:30:00Z',
    status: 'confirmed',
    createdAt: '2026-06-14T09:00:00Z',
  },
  {
    id: 'book_2',
    meetingTypeId: 'meet_60',
    guestName: 'David Lee',
    guestEmail: 'd.lee@linear-ops.net',
    guestNotes: 'Reviewing SaaS expansion capabilities and Postgres schema layouts.',
    startTime: '2026-06-17T14:00:00Z',
    endTime: '2026-06-17T15:00:00Z',
    status: 'confirmed',
    createdAt: '2026-06-14T11:15:00Z',
  }
];

export const INITIAL_FOCUS_RECORDS: FocusRecord[] = [
  {
    id: 'focus_f1',
    duration: 45,
    type: '45m',
    timestamp: '2026-06-10T10:00:00Z',
    completed: true,
    notes: 'Drafted architecture ideas.',
    breakActivityCompleted: true,
    breakActivityName: 'Mobility Reset',
  },
  {
    id: 'focus_f2',
    duration: 90,
    type: '90m',
    timestamp: '2026-06-11T14:00:00Z',
    completed: true,
    notes: 'Coding session on auth routes.',
    breakActivityCompleted: true,
    breakActivityName: 'Hydration Walk',
  },
  {
    id: 'focus_f3',
    duration: 45,
    type: '45m',
    timestamp: '2026-06-12T09:30:00Z',
    completed: true,
    notes: 'Reviewed pull requests with team.',
    breakActivityCompleted: true,
    breakActivityName: 'Focus Reset',
  },
  {
    id: 'focus_f4',
    duration: 120,
    type: '120m',
    timestamp: '2026-06-13T10:15:00Z',
    completed: true,
    notes: 'Figma UI design layout polish.',
    breakActivityCompleted: true,
    breakActivityName: 'Mobility Reset',
  },
  {
    id: 'focus_f5',
    duration: 45,
    type: '45m',
    timestamp: '2026-06-14T16:00:00Z',
    completed: true,
    notes: 'Wrote draft posts for launch.',
    breakActivityCompleted: true,
    breakActivityName: 'Hydration Walk',
  }
];

export const INITIAL_REFLECTIONS: ReflectionLog[] = [
  {
    id: 'ref_1',
    date: '2026-06-14',
    goal: 'Ensure state design works offline with custom storage syncing.',
    wins: 'Fully connected the reactive state handles and visual layouts, checked custom CSS variables.',
    lessons: 'Small screen padding needs to adapt gracefully to prevent layout compression.',
    improvements: 'Increase container spacing slightly on wider widescreen viewports.',
    createdAt: '2026-06-14T21:00:00Z',
  }
];
